services:
  postgres:
    image: postgres:16
    container_name: chat-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: realtimechat
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: chat-api
    environment:
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__Default: Host=postgres;Port=5432;Database=realtimechat;Username=postgres;Password=postgres
      JWT__Key: super_dev_secret_change_me
      JWT__Issuer: RealtimeChat
      CORS__Origin: http://localhost:3000
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: chat-client
    ports:
      - "3000:3000"
    depends_on:
      - api

volumes:
  pgdata:

